# Generated by Django 5.0 on 2023-12-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the house', max_length=50)),
                ('description', models.TextField()),
                ('country', models.CharField(help_text='country of location', max_length=200)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
